var dateToday = document.getElementById("dateToday");
dateToday.textContent = dayjs().format('M/D/YYYY h:mma');

////////Display Spotify search results on the page ////
var songTitles = document.querySelectorAll(".song-title");
var songArt = document.querySelectorAll(".album-art");
var songArtist = document.querySelectorAll(".artist-name");
var songSpotifyLink = document.querySelectorAll(".spotify-link");

///temporary json results while we work on spotify API connectivity////
var jsonFile = {
    "tracks": {
      "href": "https://api.spotify.com/v1/search?query=sunny&type=track&locale=en-US%2Cen%3Bq%3D0.9&offset=0&limit=6",
      "items": [
        {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/54R6Y0I7jGUCveDTtI21nb"
                },
                "href": "https://api.spotify.com/v1/artists/54R6Y0I7jGUCveDTtI21nb",
                "id": "54R6Y0I7jGUCveDTtI21nb",
                "name": "Boney M.",
                "type": "artist",
                "uri": "spotify:artist:54R6Y0I7jGUCveDTtI21nb"
              }
            ],
            "available_markets": [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/1KQUrny9y5zGpktF6hAGd4"
            },
            "href": "https://api.spotify.com/v1/albums/1KQUrny9y5zGpktF6hAGd4",
            "id": "1KQUrny9y5zGpktF6hAGd4",
            "images": [
              {
                "height": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b273dafd1cd6e9537ec8463ea691",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e02dafd1cd6e9537ec8463ea691",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/ab67616d00004851dafd1cd6e9537ec8463ea691",
                "width": 64
              }
            ],
            "name": "Take The Heat Off Me",
            "release_date": "1976",
            "release_date_precision": "year",
            "total_tracks": 10,
            "type": "album",
            "uri": "spotify:album:1KQUrny9y5zGpktF6hAGd4"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/54R6Y0I7jGUCveDTtI21nb"
              },
              "href": "https://api.spotify.com/v1/artists/54R6Y0I7jGUCveDTtI21nb",
              "id": "54R6Y0I7jGUCveDTtI21nb",
              "name": "Boney M.",
              "type": "artist",
              "uri": "spotify:artist:54R6Y0I7jGUCveDTtI21nb"
            }
          ],
          "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
          ],
          "disc_number": 1,
          "duration_ms": 242240,
          "explicit": false,
          "external_ids": {
            "isrc": "DED168000002"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/3pf96IFggfQuT6Gafqx2rt"
          },
          "href": "https://api.spotify.com/v1/tracks/3pf96IFggfQuT6Gafqx2rt",
          "id": "3pf96IFggfQuT6Gafqx2rt",
          "is_local": false,
          "name": "Sunny",
          "popularity": 73,
          "preview_url": "https://p.scdn.co/mp3-preview/dd07d16b7a206e52cb678355c9a061e20bc62c5e?cid=cfe923b2d660439caf2b557b21f31221",
          "track_number": 3,
          "type": "track",
          "uri": "spotify:track:3pf96IFggfQuT6Gafqx2rt"
        },
        {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/2uNpV18izVIP7DNusoWbT5"
                },
                "href": "https://api.spotify.com/v1/artists/2uNpV18izVIP7DNusoWbT5",
                "id": "2uNpV18izVIP7DNusoWbT5",
                "name": "Bobby Hebb",
                "type": "artist",
                "uri": "spotify:artist:2uNpV18izVIP7DNusoWbT5"
              }
            ],
            "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "BA",
              "BD",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FR",
              "GB",
              "GN",
              "GR",
              "GT",
              "HK",
              "HN",
              "HR",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JO",
              "JP",
              "KH",
              "KR",
              "KW",
              "LA",
              "LB",
              "LI",
              "LK",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "ME",
              "MK",
              "MT",
              "MU",
              "MX",
              "MY",
              "NG",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SE",
              "SG",
              "SI",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "UA",
              "US",
              "VE",
              "VN",
              "XK",
              "ZA"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/6pJkF95sYsVg3FJtTvTuEG"
            },
            "href": "https://api.spotify.com/v1/albums/6pJkF95sYsVg3FJtTvTuEG",
            "id": "6pJkF95sYsVg3FJtTvTuEG",
            "images": [
              {
                "height": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b273104dd939c10a2ef4fde1f1df",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e02104dd939c10a2ef4fde1f1df",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/ab67616d00004851104dd939c10a2ef4fde1f1df",
                "width": 64
              }
            ],
            "name": "Sunny",
            "release_date": "1966-01-01",
            "release_date_precision": "day",
            "total_tracks": 12,
            "type": "album",
            "uri": "spotify:album:6pJkF95sYsVg3FJtTvTuEG"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2uNpV18izVIP7DNusoWbT5"
              },
              "href": "https://api.spotify.com/v1/artists/2uNpV18izVIP7DNusoWbT5",
              "id": "2uNpV18izVIP7DNusoWbT5",
              "name": "Bobby Hebb",
              "type": "artist",
              "uri": "spotify:artist:2uNpV18izVIP7DNusoWbT5"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "BA",
            "BD",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FR",
            "GB",
            "GN",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JO",
            "JP",
            "KH",
            "KR",
            "KW",
            "LA",
            "LB",
            "LI",
            "LK",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "ME",
            "MK",
            "MT",
            "MU",
            "MX",
            "MY",
            "NG",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SE",
            "SG",
            "SI",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "UA",
            "US",
            "VE",
            "VN",
            "XK",
            "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 165066,
          "explicit": false,
          "external_ids": {
            "isrc": "USPR39402093"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/4vju55Ag7apDL2CfotuE7Q"
          },
          "href": "https://api.spotify.com/v1/tracks/4vju55Ag7apDL2CfotuE7Q",
          "id": "4vju55Ag7apDL2CfotuE7Q",
          "is_local": false,
          "name": "Sunny",
          "popularity": 70,
          "preview_url": null,
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:4vju55Ag7apDL2CfotuE7Q"
        },
        {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/4aJTB79uwT4sP0Nb8QGWHc"
                },
                "href": "https://api.spotify.com/v1/artists/4aJTB79uwT4sP0Nb8QGWHc",
                "id": "4aJTB79uwT4sP0Nb8QGWHc",
                "name": "Joe Nichols",
                "type": "artist",
                "uri": "spotify:artist:4aJTB79uwT4sP0Nb8QGWHc"
              }
            ],
            "available_markets": [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/6m1xj75U4RKEWtcyXJ7Loy"
            },
            "href": "https://api.spotify.com/v1/albums/6m1xj75U4RKEWtcyXJ7Loy",
            "id": "6m1xj75U4RKEWtcyXJ7Loy",
            "images": [
              {
                "height": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b2735239e15ce22f2afca40162ba",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e025239e15ce22f2afca40162ba",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/ab67616d000048515239e15ce22f2afca40162ba",
                "width": 64
              }
            ],
            "name": "Crickets",
            "release_date": "2013",
            "release_date_precision": "year",
            "total_tracks": 16,
            "type": "album",
            "uri": "spotify:album:6m1xj75U4RKEWtcyXJ7Loy"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4aJTB79uwT4sP0Nb8QGWHc"
              },
              "href": "https://api.spotify.com/v1/artists/4aJTB79uwT4sP0Nb8QGWHc",
              "id": "4aJTB79uwT4sP0Nb8QGWHc",
              "name": "Joe Nichols",
              "type": "artist",
              "uri": "spotify:artist:4aJTB79uwT4sP0Nb8QGWHc"
            }
          ],
          "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
          ],
          "disc_number": 1,
          "duration_ms": 206946,
          "explicit": false,
          "external_ids": {
            "isrc": "QMRSZ1700758"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/1aCDtDGqZmOzrzi62DBqGI"
          },
          "href": "https://api.spotify.com/v1/tracks/1aCDtDGqZmOzrzi62DBqGI",
          "id": "1aCDtDGqZmOzrzi62DBqGI",
          "is_local": false,
          "name": "Sunny and 75",
          "popularity": 57,
          "preview_url": "https://p.scdn.co/mp3-preview/68411afa12a9baa4c5d6ad5f5c3c667ede301b65?cid=cfe923b2d660439caf2b557b21f31221",
          "track_number": 9,
          "type": "track",
          "uri": "spotify:track:1aCDtDGqZmOzrzi62DBqGI"
        },
        {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0K7VN4aHxHcEb7PqkfoIVA"
                },
                "href": "https://api.spotify.com/v1/artists/0K7VN4aHxHcEb7PqkfoIVA",
                "id": "0K7VN4aHxHcEb7PqkfoIVA",
                "name": "Shawn Colvin",
                "type": "artist",
                "uri": "spotify:artist:0K7VN4aHxHcEb7PqkfoIVA"
              }
            ],
            "available_markets": [
              "AR",
              "AU",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/3EZXmJz03Dj8sB3K26Gmx8"
            },
            "href": "https://api.spotify.com/v1/albums/3EZXmJz03Dj8sB3K26Gmx8",
            "id": "3EZXmJz03Dj8sB3K26Gmx8",
            "images": [
              {
                "height": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b27353b24392ef405dac8c811daa",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e0253b24392ef405dac8c811daa",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/ab67616d0000485153b24392ef405dac8c811daa",
                "width": 64
              }
            ],
            "name": "A Few Small Repairs",
            "release_date": "1996-09-30",
            "release_date_precision": "day",
            "total_tracks": 12,
            "type": "album",
            "uri": "spotify:album:3EZXmJz03Dj8sB3K26Gmx8"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0K7VN4aHxHcEb7PqkfoIVA"
              },
              "href": "https://api.spotify.com/v1/artists/0K7VN4aHxHcEb7PqkfoIVA",
              "id": "0K7VN4aHxHcEb7PqkfoIVA",
              "name": "Shawn Colvin",
              "type": "artist",
              "uri": "spotify:artist:0K7VN4aHxHcEb7PqkfoIVA"
            }
          ],
          "available_markets": [
            "AR",
            "AU",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
          ],
          "disc_number": 1,
          "duration_ms": 264200,
          "explicit": false,
          "external_ids": {
            "isrc": "USSM19601709"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/4mOxpj82q6n3EO7HBZCelX"
          },
          "href": "https://api.spotify.com/v1/tracks/4mOxpj82q6n3EO7HBZCelX",
          "id": "4mOxpj82q6n3EO7HBZCelX",
          "is_local": false,
          "name": "Sunny Came Home",
          "popularity": 55,
          "preview_url": "https://p.scdn.co/mp3-preview/2b61611445aef0e42d6ee5791b2aa3bab8d5c10e?cid=cfe923b2d660439caf2b557b21f31221",
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:4mOxpj82q6n3EO7HBZCelX"
        },
        {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/5069JTmv5ZDyPeZaCCXiCg"
                },
                "href": "https://api.spotify.com/v1/artists/5069JTmv5ZDyPeZaCCXiCg",
                "id": "5069JTmv5ZDyPeZaCCXiCg",
                "name": "wave to earth",
                "type": "artist",
                "uri": "spotify:artist:5069JTmv5ZDyPeZaCCXiCg"
              }
            ],
            "available_markets": [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/0kT2Dn4QknHk92h76ZcMk0"
            },
            "href": "https://api.spotify.com/v1/albums/0kT2Dn4QknHk92h76ZcMk0",
            "id": "0kT2Dn4QknHk92h76ZcMk0",
            "images": [
              {
                "height": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b273c21555708975ad94b1faf422",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e02c21555708975ad94b1faf422",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/ab67616d00004851c21555708975ad94b1faf422",
                "width": 64
              }
            ],
            "name": "0.1 flaws and all.",
            "release_date": "2023-04-20",
            "release_date_precision": "day",
            "total_tracks": 14,
            "type": "album",
            "uri": "spotify:album:0kT2Dn4QknHk92h76ZcMk0"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/5069JTmv5ZDyPeZaCCXiCg"
              },
              "href": "https://api.spotify.com/v1/artists/5069JTmv5ZDyPeZaCCXiCg",
              "id": "5069JTmv5ZDyPeZaCCXiCg",
              "name": "wave to earth",
              "type": "artist",
              "uri": "spotify:artist:5069JTmv5ZDyPeZaCCXiCg"
            }
          ],
          "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
          ],
          "disc_number": 1,
          "duration_ms": 248746,
          "explicit": false,
          "external_ids": {
            "isrc": "KRA252300808"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/4U9teFThcaHZz386DQM6FY"
          },
          "href": "https://api.spotify.com/v1/tracks/4U9teFThcaHZz386DQM6FY",
          "id": "4U9teFThcaHZz386DQM6FY",
          "is_local": false,
          "name": "sunny days",
          "popularity": 71,
          "preview_url": "https://p.scdn.co/mp3-preview/f66c85518f307673552b138a7279366818caf695?cid=cfe923b2d660439caf2b557b21f31221",
          "track_number": 2,
          "type": "track",
          "uri": "spotify:track:4U9teFThcaHZz386DQM6FY"
        },
        {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/35l9BRT7MXmM8bv2WDQiyB"
                },
                "href": "https://api.spotify.com/v1/artists/35l9BRT7MXmM8bv2WDQiyB",
                "id": "35l9BRT7MXmM8bv2WDQiyB",
                "name": "beabadoobee",
                "type": "artist",
                "uri": "spotify:artist:35l9BRT7MXmM8bv2WDQiyB"
              }
            ],
            "available_markets": [
              "AR",
              "AU",
              "AT",
              "BE",
              "BO",
              "BR",
              "BG",
              "CA",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DK",
              "DO",
              "DE",
              "EC",
              "EE",
              "SV",
              "FI",
              "FR",
              "GR",
              "GT",
              "HN",
              "HK",
              "HU",
              "IS",
              "IE",
              "IT",
              "LV",
              "LT",
              "LU",
              "MY",
              "MT",
              "MX",
              "NL",
              "NZ",
              "NI",
              "NO",
              "PA",
              "PY",
              "PE",
              "PH",
              "PL",
              "PT",
              "SG",
              "SK",
              "ES",
              "SE",
              "CH",
              "TW",
              "TR",
              "UY",
              "US",
              "GB",
              "AD",
              "LI",
              "MC",
              "ID",
              "JP",
              "TH",
              "VN",
              "RO",
              "IL",
              "ZA",
              "SA",
              "AE",
              "BH",
              "QA",
              "OM",
              "KW",
              "EG",
              "MA",
              "DZ",
              "TN",
              "LB",
              "JO",
              "PS",
              "IN",
              "BY",
              "KZ",
              "MD",
              "UA",
              "AL",
              "BA",
              "HR",
              "ME",
              "MK",
              "RS",
              "SI",
              "KR",
              "BD",
              "PK",
              "LK",
              "GH",
              "KE",
              "NG",
              "TZ",
              "UG",
              "AG",
              "AM",
              "BS",
              "BB",
              "BZ",
              "BT",
              "BW",
              "BF",
              "CV",
              "CW",
              "DM",
              "FJ",
              "GM",
              "GE",
              "GD",
              "GW",
              "GY",
              "HT",
              "JM",
              "KI",
              "LS",
              "LR",
              "MW",
              "MV",
              "ML",
              "MH",
              "FM",
              "NA",
              "NR",
              "NE",
              "PW",
              "PG",
              "WS",
              "SM",
              "ST",
              "SN",
              "SC",
              "SL",
              "SB",
              "KN",
              "LC",
              "VC",
              "SR",
              "TL",
              "TO",
              "TT",
              "TV",
              "VU",
              "AZ",
              "BN",
              "BI",
              "KH",
              "CM",
              "TD",
              "KM",
              "GQ",
              "SZ",
              "GA",
              "GN",
              "KG",
              "LA",
              "MO",
              "MR",
              "MN",
              "NP",
              "RW",
              "TG",
              "UZ",
              "ZW",
              "BJ",
              "MG",
              "MU",
              "MZ",
              "AO",
              "CI",
              "DJ",
              "ZM",
              "CD",
              "CG",
              "IQ",
              "LY",
              "TJ",
              "VE",
              "ET",
              "XK"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/2rhNQbqRNxiNQkDXTffe1V"
            },
            "href": "https://api.spotify.com/v1/albums/2rhNQbqRNxiNQkDXTffe1V",
            "id": "2rhNQbqRNxiNQkDXTffe1V",
            "images": [
              {
                "height": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b273384d10f967c2b914de7e2713",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e02384d10f967c2b914de7e2713",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/ab67616d00004851384d10f967c2b914de7e2713",
                "width": 64
              }
            ],
            "name": "Beatopia",
            "release_date": "2022-07-15",
            "release_date_precision": "day",
            "total_tracks": 14,
            "type": "album",
            "uri": "spotify:album:2rhNQbqRNxiNQkDXTffe1V"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/35l9BRT7MXmM8bv2WDQiyB"
              },
              "href": "https://api.spotify.com/v1/artists/35l9BRT7MXmM8bv2WDQiyB",
              "id": "35l9BRT7MXmM8bv2WDQiyB",
              "name": "beabadoobee",
              "type": "artist",
              "uri": "spotify:artist:35l9BRT7MXmM8bv2WDQiyB"
            }
          ],
          "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
          ],
          "disc_number": 1,
          "duration_ms": 160493,
          "explicit": false,
          "external_ids": {
            "isrc": "GBK3W2202090"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/12UQIJePnGeLmpVReYpG2w"
          },
          "href": "https://api.spotify.com/v1/tracks/12UQIJePnGeLmpVReYpG2w",
          "id": "12UQIJePnGeLmpVReYpG2w",
          "is_local": false,
          "name": "Sunny day",
          "popularity": 67,
          "preview_url": "https://p.scdn.co/mp3-preview/07699436f1bd803a21b8af94b3c857710547cad0?cid=cfe923b2d660439caf2b557b21f31221",
          "track_number": 3,
          "type": "track",
          "uri": "spotify:track:12UQIJePnGeLmpVReYpG2w"
        }
      ],
      "limit": 6,
      "next": "https://api.spotify.com/v1/search?query=sunny&type=track&locale=en-US%2Cen%3Bq%3D0.9&offset=6&limit=6",
      "offset": 0,
      "previous": null,
      "total": 164
    }
};

console.log(jsonFile);
function updateSongCards(jsonFile) {
    var songsArray = [];
    for (let i=0; i<6; i++){
        var title = jsonFile["tracks"]["items"][i]["name"];
        var artist = jsonFile["tracks"]["items"][i]["album"]["artists"][0]["name"];
        var songURL = jsonFile["tracks"]["items"][i]["external_urls"]["spotify"];
        console.log(title, "_", artist, "_", songURL);
        var song = [title, artist, songURL];
        songsArray.push(song);
        console.log(songsArray); 
    };
    songTitles.forEach(function(title, index) {
        title.textContent = songsArray[index][0];
    });

    songArtist.forEach(function(artist, index) {
        artist.textContent = songsArray[index][1];
    });

    songSpotifyLink.forEach(function(link, index) {
        link.href = songsArray[index][2];
    });
}

updateSongCards(jsonFile);
